language: python
python:
  - "3.9" # github 에 push 할 때마다 3.9버전의 python을 

services:
  - docker # sub service는 dockerfile 이나 docker-compose.yml 파일에 기재되어있다. 

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"

